### ISSUE TITLE
Use admin packages/ Ignore route

### ISSUE THREAD

**Issue by zimt28** [yoolab/iron-router-i18n#24]
I just tried some different packages that give me an admin interface for my app, `orionjs:core` and `houston:admin`. Both of them give me an `/admin` route to see the backend. However, I always get redirected to `/de/admin` and the interfaces won't show up. Is there a way I can ignore the `/admin` route to use these packages?

**Comment by martinopic** [comment]
Sorry I missed this ticket. In order to ignore redirect on specific routes you can just override default `missingLangCodeAction` method in configuration. E.g.

```javascript
Router.configure({

    i18n: {

      missingLangCodeAction: function(path, options) {
         if (path == '/admin') {
            return;
         }

         ....
     }

    }

})
```

**Comment by zimt28** [comment]
Cool, works great :) Thanks!

**Comment by Tim-W** [comment]
Please document this on the readme file. It took me quite a while to find this resolution.

**Comment by martinopic** [comment]
@Tim-W, it's documented in the "exclude" configuration parameters section on the README. This ticket is outdates as there is now a standard method to exclude specific routes/paths.
