### ISSUE TITLE
using getLanguage() for Meteor.user().getLanguage attribute

### ISSUE THREAD

**Issue by dohomi** [yoolab/iron-router-i18n#26]
Hi @martinopic 

I just tried the approach using following syntax on the newest 0.5.x version:

```
Router.configure({
  layoutTemplate: 'layoutBackend',
  notFoundTemplate: 'page404',
  loadingTemplate: 'loading',
  i18n: {
    languages: TP.Const.AllowedLangKey,
    getLanguage: function () {
      if (Meteor.loggingIn()) {
        return;
      }
      var userLangKey = Meteor.user() && Meteor.user().languageKey;
      return userLangKey;
    },
(...)
```

But this results into an endless loop if I use several ```Router.go()```.
Any idea on this?

Cheers

**Comment by dohomi** [comment]
I tried a lot but couldn't set the language through any function, tried in layout templates with ```Router.setLanguage()``` and tried with the ```getLanguage()``` function above. The problem is, that if I have 'de' as user language and route through a ```Router.go('dashboard')``` the routing fails completely, because my browser language is 'en' and the ```depend()```falls back to the previous route.

Any idea how to set this right? Thanks!

**Comment by dohomi** [comment]
Here is a small reproduction application, i looks like Router.go does not take the current language into account

**Comment by martinopic** [comment]
"here" where? :-)

**Comment by dohomi** [comment]
sorry little browser issue here :)

**Comment by dohomi** [comment]
So we stumbled into major issue while trying to use ```Router.go()```, it always falls back to default /en, and though we ran into reactiveVar issue and endless looping between get and set language.

**Comment by martinopic** [comment]
thanks alot @dohomi I'll look into it today.

**Comment by dohomi** [comment]
Thanks just drop me a message if I could do some testing.

**Comment by martinopic** [comment]
Ok, I understand the problem: the fact is that basically you are calling ```Router.go('something')``` and you expect I18NRouter to route you as if it was ```Router.go('de.something')``` if current language is "de" while I18NRouter is behaving as if you called the "default" route (which in this case is an "en" route). 

This was actually made on purpose but your case made me think and I now believe it's more natural the behaviour you were expecting.

P.S.

there is also a mistake at line 19, it should be ```return Session.get("lang");```, missing ```return```, with the commit below and adding the return the sample app will work. Thanks once again for your help!
