### ISSUE TITLE
Router is forwading to getLanguage() even I sent the /en or /de param

### ISSUE THREAD

**Issue by dohomi** [yoolab/iron-router-i18n#28]
Hi @martinopic 

I bump into an issue, where I want to open a link which is published somewhere:

/en/db/my-exercise

In ```getLanguage()``` I set the language based on the ```Meteor.users().languageKey``` or based on the browser. Now the plugin seems to force setting ```/de/db/my-exercise``` which is non-existent and the ```page_404``` template is getting rendered.

This wasn't the same behaviour than before? Do you have an idea if something in my code might be wrong or is something missing in the ```0.5.x``` branch?
Cheers!

**Comment by martinopic** [comment]
I'm having serious problems publishing the entire package so I had to comment some code, see #29 not sure if this is related (I might have messed up some code trying to overstep the problem but still: all tests are passing).

**Comment by martinopic** [comment]
Ok, fixed #29, it had nothing to specifically do with this but there was a mess with the published 0.5.0 version code (I thought meteor tool had a way to unpublish a release I had published just to test meteor publish itself :-) )

I think you are referring to the same problem reported before in #26 right? I'll look into that but note that 0.5.x is no longer used, after the release I'm using master branch (and just published 0.5.1).

**Comment by dohomi** [comment]
I just updated my source code of https://github.com/dohomi/i18napp. There is now a user login and a user ```testuser@example.com```and password ```123123```. This user is has languageKey ```de```but default language is ```en```.

Mow you can see misbehaviour and endless routing in some point. And if you post /en/foo to a user it also bumps into some issue. 

Not sure how to solve this, but I think the current language should be:
-> first check current route if langKey is set
-> check getLanguage() in i18n 
-> fallback into browser language or some other default

Not sure if I mess up my config but currently some weird ```404```showing up.

**Comment by martinopic** [comment]
The problem is in your app ```getLanguage``` configuration: this is intended to be read as "get the router language" while your code now always return the user language. As the user language is "de" the router language for this user will always be "de". Given the ```setLanguage``` you have you sample app should just be

```
getLanguage: function (lang) {
      return Session.get("lang");
    },

```

As it actually was before.

I'd just use the user account langKey just to initially set the router language when the user logs but if the user later on decide to switch to an "en" route the setLanguage/getLanguage methods should just give this possibility and not use again the langKey. Please tell me if you find anything not clear in this logic or in the methods documentation so that I can improve it.

**Comment by dohomi** [comment]
I try to get anything better to run than calling ```Router.setLanguage()``` inside a ```Template.foo.rendered``` helper to get this done. In my opinion there is a function missing like ```getInitLanguage()``` where I could paste in some logic for user based language which is not getting called after ```Router.setLanguage()```.

Otherwise I will stick to my previous handling and paste the ```Router.setLanguage()```into the rendered function of my layout and add the logic to see if there is already a ```langCode``` inside of the url. Couldn't find any better or different spot for this call.

**Comment by dohomi** [comment]
Sorry I missed my very first idea: 

Currently on page reload "setLanguage()" is not getting called. Only on user handling. So your current example with 
```
setLanguage:function(lang){
     TAPi18n.setLanguage(lang);
}
```
Is only setting the language on user interaction. But where do I have to paste the code to set my language for ```TAPi18n.setLanguage()```that the page content would be initially set on page loading?

**Comment by martinopic** [comment]
The code you put now in ```getLanguage``` is totally unnecessary: iron router i18n will automatically switch language (i.e. call ```Router.setLanguage``` which also call YOUR overridden ```setLanguage``` if any).

why not using a simple

```
Meteor.startup(function() {

  if ((Meteor.user() && Meteor.user().languageKey)) {
    Router.setLanguage(Meteor.user().languageKey)
  }

});

```

If the user is not logged ```getLanguage``` would just return default language (otherwise you can handle this case in startup too.

**Comment by dohomi** [comment]
Isn't Meteor.startup only getting called once if I'm not mistaken? So what if a user logs out and in again?

**Comment by martinopic** [comment]
If a user logs in/logs out you should handle that specific event:

```
Meteor.autorun(function() {
  if (Meteor.userId()) {
    Router.setLanguage(Meteor.user().languageKey);
  }
});
```
I wouldn't handle log out, it makes sense leaving the logged out user language.

**Comment by dohomi** [comment]
Ok I'm doing it similar:
```


Template.body.rendered = function () {
  this.autorun(function () {
    var langCodeMissing = TP.initLangCodeMissing;
    var userLang = Meteor.user() && Meteor.user().languageKey;
    var currentRouterLanguage = Router.getLanguage();
    if (langCodeMissing && !Meteor.loggingIn() && userLang) {
      if (userLang !== currentRouterLanguage) {
        Router.setLanguage(userLang);
      }
    } else {
      if (currentRouterLanguage !== TP.Core.Functions.getLanguageKey()) {
        TP.Core.Functions.setLanguageKey(currentRouterLanguage);
      }
    }
  });
};
```

**Comment by dohomi** [comment]
But still I think it would be convenient if the last 
```
      if (currentRouterLanguage !== TP.Core.Functions.getLanguageKey()) {
        TP.Core.Functions.setLanguageKey(currentRouterLanguage);
      }
```
should be handled by this package. Otherwise the language package is on page reload never updated with the current language. I will close this issue now because I think it works (beside the PR from Max) quite stable.

**Comment by martinopic** [comment]
I don't exactly see how the package could abstractly manage this thing: it seems something related to how you handle language inside your project, that is why is given a possibility to configure additional ```setLanguage```/```getLanguage``` behaviours. Please clarify me if I get anything wrong.

**Comment by dohomi** [comment]
You have an example of 
```
setLanguage:function(lang){
     TAPi18n.setLanguage(lang);
}
```
inside of your ```Readme```. So I guess users would think if they set this every user would see their language in their browser specific language by default. But they only would see it if they have registered an
```
Deps.autorun(function(){
 TAPi18n.setLanguage(Router.getLanguage()); 
}); 
```
Correct me if I'm wrong. I just thought in the beginning that ```setLanguage```would take care of my ```TAPi18n```language handling from the beginning.

Here my usecase:

On my website I have 2 languages. Two users, one with a german browser and one with an english browser are entering the website (without logged in - so pure default handling). 

German --> /de/home but english labels because TAPi18n is set to en per default
English --> /en/home with english labels (all good)

Inside of your ```Readme```it would be helpful that people needs to know that they must add the code additionaly - because every user who will use your package must use any other i18n package to translate the labels.

But I'm fine with the handling now :+1:
