### ISSUE TITLE
How to enhance Iron Router and relate to other Iron Router modules

### ISSUE THREAD

**Issue by martinopic** [yoolab/iron-router-i18n#32]
It seems that there is some problem with the mechanism through which the package replace "Router" with I18NRouter: the old "Router" is in fact left around and used in some closures defined before Iron Router i18n is able to override it. This is might also be due to the fact that Iron Router package instantiate the Router object itself.

This might give problems with other existing Iron Router packages (#27) but also with helpers refactoring done in this commit: d1f5adf3c1a112674250dfbdc1c24806c5571c07

**Comment by zimme** [comment]
How about extending Router instead of replacing it completely?

**Comment by martinopic** [comment]
That was my previous approach with 0.4.x (that is not iron router 1.0 compatible). It makes testing more difficult and, in my opinion, is less "clean" but I'm considering it. Thanks.

**Comment by martinopic** [comment]
Finally I decided for an approach taking both ways: extending the Route main object (so to play better with other iron router modules and follow Iron Router main object strategy) AND extending Iron.Router.prototype so to ease testing and follow the same Iron Router prototypal inheritance system.
