### ISSUE TITLE
Calling Router.setLanguage(lang) from onSignIn error

### ISSUE THREAD

**Issue by obiwarn** [yoolab/iron-router-i18n#49]
When I call Router.setLanguage(lang) from my onSignIn method (when user logs in), it changes my Language but not the url.
When I call it anywhere (e.g. click event) else everything is working fine.

My onSignIn method is called from AccountsTemplates Package hook:

AccountsTemplates.configure(
    onSubmitHook: (error, state) ->
        Login.onSignIn(error, state)
        return
)

**Comment by martinopic** [comment]
I don't see any general reason why this should happen. The package is tested with user sign in, I need some more information on your actual code or, possibly, some "toy app" showing the problematic behaviour in order to further investigate it.

**Comment by martinopic** [comment]
Haven't received any further feedback on this for two weeks, closing.
