### ISSUE TITLE
404 handling

### ISSUE THREAD

**Issue by zimt28** [yoolab/iron-router-i18n#54]
When I open my app with a route that doesn't exist, I get my error screen. [This line](https://github.com/yoolab/iron-router-i18n/blob/7a193da9f834cc5ecfa75bc3a81d0625483132f1/lib/router_client.js#L60) seems to break my app then, as the non-existent route doesn't have a `name`. So using `getName()` won't work.

**Comment by martinopic** [comment]
I've added an additional check on current ```controller.route``` but I can't repeat the bug. Could you tell me the steps to reproduce it with ```examples/basic``` application and/or by integrating it with some additional conf? I don't know exactly how are you managing the 404 stuff.
