### ISSUE TITLE
Locale-independent URL

### ISSUE THREAD

**Issue by Geen-Henk** [yoolab/iron-router-i18n#55]
Question:

Is it possible to generate a locale-independent URL? In my case I'm making some sort of builder/calculator and I want to generate a link for people to be able to share the build/calculation to other people, that then can view it in their own language.

When I generate a link like this:

```coffeescript
permalink: -> Router.routes['calculator'].url
  concatenatedParams: [
    Session.get("calc-param-1")
    Session.get("calc-param-2")
    Session.get("calc-param-3")
    Session.get("calc-param-4")
    Session.get("calc-param-5")
  ].join("_")
```

I get the URL with the current locale, i.e. `http://example.com/en/calculator/1_2_3_4_5`.
Now I'd like to get the following URL: `http://example.com/calculator/1_2_3_4_5`, so that It chooses the appropriate locale, like it does when I visit that last link.

Is this possible? For example, by using `Router.routes['calculator'].urlNoLocale` instead of just `url`.

**Comment by martinopic** [comment]
If I got it right you are referring to the possibility to have ```Route.path``` or ```pathFor``` helper return the url/path without language code and then have iron-router-i18n to automatically redirect to the correct language code aware url. This latter thing is already there, what's not currently possible is to have the "urlNoLocale" path, I think it's a reasonable feature so I'll try to add it to the next release.

**Comment by Geen-Henk** [comment]
You got it exactly right, thanks! :+1: 
Indeed the latter works, quote: "like it does when I visit that last link".

**Comment by martinopic** [comment]
This is my attempt to model your request in iron-router-i18n:

```javascript
Router.routes['post'].path({_id: 23}, {origRoute: true}
```

will return ```/post/23```

```javascript
{{pathFor name="about" origRoute=true}}
```

will return ```/about``` (instead of e.g. ```/en/about```)

To access the original route you can use ```Router.routes['routeName'].origRoute```

When ```langCodeForDefaultLanguage``` is set to ```false``` this will just return the default route (the route for the default language).

The patch is in master, I've got some test coverage for this but it'd be good to have some feedback and some real world test. If everything is ok it'll be in next release.

**Comment by Geen-Henk** [comment]
Sweet, Ill go ahead and test it.

**Comment by Geen-Henk** [comment]
Just a question: How do I use the master? I removed Meteor package and extracted all files in `lib/` to my `lib/iron-router-i18n/` folder

**Comment by martinopic** [comment]
you have to create a "packages" folder and put master content there in a subfolder named "martino:iron-router-i18n" (as for any "custom" meteor package)

**Comment by Geen-Henk** [comment]
Ah ok thanks! Haven't installed a custom package before so I didn't know.

**Comment by Geen-Henk** [comment]
Awesome, both helpers work as expected :+1:

**Comment by martinopic** [comment]
Great :+1:  . I'll keep the issue open because I might change the parameter name and/or some other configuration parameters but the feature should stay the same. Thanks for your suggestion and your help.
