### ISSUE TITLE
[Question] How can I localize title in head?

### ISSUE THREAD

**Issue by y-ich** [yoolab/iron-router-i18n#60]
Now I localize page title using onBeforeAction like the following code.

``` coffeescript
Router.route '/foo',
    onBeforeAction: ->
        document.title = TAPi18n.__ 'fooTitle'
        @next()
```

Are there any simpler implementations?

**Comment by martinopic** [comment]
This is not really Iron Router i18n related but why don't you just use tap-i18n helper in the layout template? Not sure whether tap-i18n translate helper is reactive if it's not you can just make your reactive one and/or use a tracker and put a dependency on current language.

**Comment by y-ich** [comment]
Helpers in head tag do not work. Spacebars just renders '{{XXX}}' string.
Anway, thank you!

**Comment by martinopic** [comment]
You can probably use a package like

https://atmospherejs.com/lookback/seo

or

https://atmospherejs.com/rainhaven/iron-seo

Just search for "meta" in Atmosphere.
