### ISSUE TITLE
Use tap:i18n in basic example

### ISSUE THREAD

**Issue by jirkadev** [yoolab/iron-router-i18n#65]
Hi, would it be possible to improve your examples\basic with integration of tap:i18n package. I wanted to have page content translated:

http://localhost:3000/en/one -> Page one
http://localhost:3000/it/one -> Prima pagina

I installed tap:i18n an added en.i18n.json and it.i18n.json, but it did not translate page for different url, but it should. I am new to Meteor and I don't know how to integrate these two packages. It would take you few minutes to improve your example. Thank you very much

**Comment by martinopic** [comment]
Examples need to be redone completely as weren't kept up to date with changes.

**Comment by jirkadev** [comment]
Thank you:)

**Comment by jirkadev** [comment]
It would be nice, if you add a language switcher in you example. I mean this package: [tap:i18n-ui](https://atmospherejs.com/tap/i18n-ui)

Example with packages: iron-router-i18n, tap:i18n and tap:i18n-ui would be nice.
I mean to have two languages and two sample pages. And different URLs for each language. Something like switching languages on Wikipedia:)

**Comment by martinopic** [comment]
It was this way before it broke, just very rough design (if somebody is willing to give a hand on this I'd be glad :-) ). Language switcher were just links and a listener on these links.

**Comment by martinopic** [comment]
I've written two very simple but working examples one without tap-i18n (bare iron-route-i18n) and one with tap-i18n integration.
