### ISSUE TITLE
An error occurs at 1.1.0 version

### ISSUE THREAD

**Issue by y-ich** [yoolab/iron-router-i18n#67]
Hi.

When I update Meteor to 1.1.0.3, meteor automatically updates iron-router-i18n to 1.1.0 and I became to get an error "Uncaught Error: Router.route requires a path that is a string or regular expression." in iron_core.js.

I guess that this error is related with iron-router-i18n since Iron Router has no change for meteor 1.1.0.3.

**Comment by martinopic** [comment]
Please try to use [issue-63 branch version](https://github.com/yoolab/iron-router-i18n/archive/issue-63.zip) and see if it solve this problem. I've been reported some problems about 1.1 version also in #63 but I really can't figure out exactly where is the problem (if any). See the discussion on the issue on what was changed and why (just an internal implementation).

**Comment by y-ich** [comment]
I found the cause and made a pull request #68.
